# Copyright (c) 2024 Contributors to COVESA
#
# This program and the accompanying materials are made available under the
# terms of the Mozilla Public License 2.0 which is available at
# https://www.mozilla.org/en-US/MPL/2.0/
#
# SPDX-License-Identifier: MPL-2.0

name: viss_build

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Building
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb 
        google-chrome-stable --headless --print-to-pdf=VISSv3.0_Core.pdf spec/VISSv3.0_Core.html
        google-chrome-stable --headless --print-to-pdf=VISSv3.0_TransportExamples.pdf spec/VISSv3.0_TransportExamples.html
        google-chrome-stable --headless --print-to-pdf=VISSv3.0_PayloadEncoding.pdf spec/VISSv3.0_PayloadEncoding.html

    - name: "Upload PDFs"
      uses: actions/upload-artifact@v4
      with:
        name: viss-pdfs
        path: '*.pdf'

